run_config:
  name: phishing-detection-project
  author: MSiA 423 Group 1
  version: default
  description: Classifies urls into phishing or legitimate webpages.
  dependencies: requirements.txt
  output: artifacts

aws:
  upload: False
  bucket_name: phishing-project
  file_key: data/dataset_phishing.csv
  prefix: artifacts/

process_data:
  drop_columns:
    - url
    - nb_or
    - ratio_nullHyperlinks
    - ratio_intErrors
    - ratio_intRedirection
    - submit_email
    - sfh
  drop_duplicates: true
  drop_na: true
  correlated_columns: 
    - ratio_extHyperlinks
    - longest_words_raw
  external_features:
    - whois_registered_domain
    - domain_registration_length
    - domain_age
    - web_traffic
    - dns_record
    - google_index
    - page_rank
  status_mapping:
    legitimate: 0
    phishing: 1
  
generate_features:
  standardize_prefix: nb_
  standardize_by: length_url

train_model:
  split:
    test_size: 0.2
    test_size_validation: 0.1
    random_state: 42
    cv: 3
  grid_search:
    RandomForest:
      n_estimators: [50, 100, 500, 1000]
      max_depth: [1, 3, 5, 10]
      min_samples_split: [2, 4, 5, 10]
    XGBoost:
      max_depth: [3, 5, 7, 9]
      learning_rate: [0.1, 0.03, 0.01]
      n_estimators: [50, 100, 200, 500]

visualize_results:
  confusion_matrix_filename: confusion_matrix.png
  classification_report_filename: classification_report.png
  roc_curve_filename: roc_curve.png
