run_config:
  name: phishing-detection-project
  author: MSiA 423 Group 1
  version: default
  description: Classifies urls into phishing or legitimate webpages.
  dependencies: requirements.txt
  output: artifacts

aws:
  upload: True
  bucket_name: phishing-project
  file_key: data/dataset_phishing.csv
  prefix: artifacts/

process_data:
  drop_columns:
    - url
    - nb_or
    - ratio_nullHyperlinks
    - ratio_intErrors
    - ratio_intRedirection
    - submit_email
    - sfh
  drop_duplicates: true
  drop_na: true
  correlated_columns: 
    - ratio_extHyperlinks
    - longest_words_raw
  external_features:
    - whois_registered_domain
    - domain_registration_length
    - domain_age
    - web_traffic
    - dns_record
    - google_index
    - page_rank
  status_mapping:
    legitimate: 0
    phishing: 1
  
generate_features:
  standardize_prefix: "nb_"
  standardize_by: "length_url"

train_model:
  split:
    test_size: 0.2
    random_state: 373
  RandomForest:
    n_estimators: 1000
    min_samples_split: 5
    max_depth: ~
    random_state: 373
  XGBoost:
    n_estimators: 500
    learning_rate: 0.1
    max_depth: 9
